version: "3.9"

services:
  # ----- Database -----
  wallet-service-db:
    image: postgres:17.0
    container_name: wallet-service-db

    env_file:
      - ./config.env

    volumes:
      - wallet_service_db_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 1s
      timeout: 3s
      retries: 30

    ports:
      - "5432:5432"
    restart: always
    networks:
      - wallet-service-network

  # ----- Service -----
  wallet-service:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    container_name: wallet-service
    
    environment:
      - CONFIG_PATH=/app/config.env
    
    env_file:
      - ./config.env

    depends_on:
      wallet-service-db:
        condition: service_healthy

    ports:
      - "8080:80"
    restart: always
    networks:
      - wallet-service-network

volumes:
    wallet_service_db_data:

networks:
  wallet-service-network:
    driver: bridge
